[package]
name = "each_cmd"
version = "0.1.0"
authors = ["Chen Weiguang <chen.weiguang@gmail.com>"]

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
error-chain = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.0"
structopt-derive = "0.0"
tokio-timer = "0.1"
